Document: mtail
Title: Debian mtail Manual
Author: <insert document author here>
Abstract: This manual describes what mtail is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mtail/mtail.sgml.gz

Format: postscript
Files: /usr/share/doc/mtail/mtail.ps.gz

Format: text
Files: /usr/share/doc/mtail/mtail.text.gz

Format: HTML
Index: /usr/share/doc/mtail/html/index.html
Files: /usr/share/doc/mtail/html/*.html
